export default {
  SEE_DOCUMENTS: 'Visualizar documentos',
  CREATE_DOCUMENTS: 'Criar documentos',
  UPDATE_DOCUMENTS: 'Atualizar documentos',
  DELETE_DOCUMENTS: 'Deletar documentos',
  SEE_CLIENTS: 'Visualizar clientes',
  CREATE_CLIENTS: 'Criar clientes',
  UPDATE_CLIENTS: 'Atualizar clientes',
  DELETE_CLIENTS: 'Deletar clientes',
  SEE_DOCUMENT_TYPES: 'Visualizar tipos de documentos',
  CREATE_DOCUMENT_TYPES: 'Criar tipos de documentos',
  UPDATE_DOCUMENT_TYPES: 'Atualizar tipos de documentos',
  DELETE_DOCUMENT_TYPES: 'Deletar tipos de documentos',
  SEE_DOCUMENT_NATURES: 'Visualizar naturezas de documentos',
  CREATE_DOCUMENT_NATURES: 'Criar naturezas de documentos',
  UPDATE_DOCUMENT_NATURES: 'Atualizar naturezas de documentos',
  DELETE_DOCUMENT_NATURES: 'Deletar naturezas de documentos',
  SEE_DOCUMENT_LOCATION: 'Visualizar localizações de documentos',
  CREATE_DOCUMENT_LOCATION: 'Criar localizações de documentos',
  UPDATE_DOCUMENT_LOCATION: 'Atualizar localizações de documentos',
  DELETE_DOCUMENT_LOCATION: 'Deletar localizações de documentos',
  SEE_USERS: 'Visualizar usuários',
  CREATE_USERS: 'Criar usuários',
  UPDATE_USERS: 'Atualizar usuários',
  DELETE_USERS: 'Deletar usuários',
};
